### ISSUE TITLE
MAPA MENTAL WEB 3.0

### ISSUE THREAD

**Issue by MAB288** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-MAB288#1]
[MARTINEZ_CHOLULA_MAVIEL_MAPA_MENTAL_WEB 3.0.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-MAB288/files/14491809/MARTINEZ_CHOLULA_MAVIEL_MAPA_MENTAL_WEB.3.0.pdf)

**Comment by carlos0716c** [comment]
18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
